name: Deploy to Google Cloud for userAuth-service

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ctse-autopilot-cluster-1  # Change this to your cluster's name 11111
  GKE_ZONE: asia-south2    # Change this to your cluster's zone
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/userauth-service-image:latest

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image
      run: |
        gcloud builds submit --tag $IMAGE --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install kubectl
      run: gcloud components install kubectl
  
    - name: Install GKE gcloud Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        echo "PATH=$PATH:/opt/hostedtoolcache/gcloud/472.0.0/x64/bin" >> $GITHUB_ENV

    - name: Set up Kubectl
      run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/k8s.yaml --validate=false
        kubectl rollout status deployment/userAuth-service-web-app-deployment

    - name: Verify deployment
      run: kubectl get all

